# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directories: 
      - "dotnet/images" # Location of package manifests
      - "go/images"
      - "python/images"
      - "java/images"
      - "misc/"
    schedule:
      interval: "daily"
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      base-images:
        applies-to: version-updates
        update-types:
          - "major"
          - "minor"
          - "patch"
